import React, { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'en' | 'hi' | 'kn';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    appName: 'Urban Lens',
    tagline: 'AI-Powered Civic Infrastructure Tracker',
    heroDesc: 'Report potholes, garbage dumps & broken streetlights. AI validates, deduplicates, and routes to your municipal ward.',
    login: 'Login',
    signup: 'Sign Up',
    home: 'Home',
    about: 'About',
    howItWorks: 'How It Works',
    reportIssue: 'Report Civic Issue',
    citizen: 'Citizen',
    officer: 'Municipal Officer',
    admin: 'Admin',
    selectRole: 'Select your role to continue',
    welcome: 'Welcome Back',
    createAccount: 'Create Account',
    joinUrbanLens: 'Join Urban Lens',
    helpCity: 'Help build a safer, cleaner city',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    fullName: 'Full Name',
    phone: 'Phone Number',
    address: 'Address',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    backToRoles: '← Back to role selection',
    citizenLogin: 'Citizen Login',
    officerLogin: 'Officer Login',
    adminPortal: 'Admin Portal',
    reportDesc: 'Report issues & earn civic points',
    officerDesc: 'Review & resolve assigned issues',
    adminDesc: 'Analytics, monitoring & management',
    newToCivic: 'New to Urban Lens?',
    createCitizenAccount: 'Create a Citizen Account →',
    aiDetection: 'AI Detection',
    aiDetectionDesc: 'Smart pothole & garbage recognition',
    geoDedup: 'Geo Deduplication',
    geoDedupDesc: 'Prevents duplicate reports within 10m',
    gamification: 'Gamification',
    gamificationDesc: 'Earn points and badges for reports',
    wardRouting: 'Ward Routing',
    wardRoutingDesc: 'Issues routed to correct municipal ward',
    teamCredit: 'Team Techno-5 · BMSCE Hackathon 2026',
    builtWith: 'Built with AI + PostGIS + React Native',
    footerRights: '© 2026 Urban Lens. All rights reserved.',
    footerMission: 'Empowering citizens to build smarter cities.',
    language: 'Language',
  },
  hi: {
    appName: 'अर्बन लेंस',
    tagline: 'AI-संचालित नागरिक बुनियादी ढांचा ट्रैकर',
    heroDesc: 'गड्ढे, कूड़े के ढेर और टूटी स्ट्रीटलाइट की रिपोर्ट करें। AI सत्यापित करता है और आपके नगरपालिका वार्ड में भेजता है।',
    login: 'लॉगिन',
    signup: 'साइन अप',
    home: 'होम',
    about: 'हमारे बारे में',
    howItWorks: 'यह कैसे काम करता है',
    reportIssue: 'नागरिक समस्या रिपोर्ट करें',
    citizen: 'नागरिक',
    officer: 'नगरपालिका अधिकारी',
    admin: 'व्यवस्थापक',
    selectRole: 'जारी रखने के लिए अपनी भूमिका चुनें',
    welcome: 'वापस स्वागत है',
    createAccount: 'खाता बनाएं',
    joinUrbanLens: 'अर्बन लेंस से जुड़ें',
    helpCity: 'एक सुरक्षित, स्वच्छ शहर बनाने में मदद करें',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    email: 'ईमेल',
    fullName: 'पूरा नाम',
    phone: 'फोन नंबर',
    address: 'पता',
    signIn: 'साइन इन',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    backToRoles: '← भूमिका चयन पर वापस',
    citizenLogin: 'नागरिक लॉगिन',
    officerLogin: 'अधिकारी लॉगिन',
    adminPortal: 'व्यवस्थापक पोर्टल',
    reportDesc: 'समस्याएं रिपोर्ट करें और अंक कमाएं',
    officerDesc: 'सौंपी गई समस्याएं समीक्षा और हल करें',
    adminDesc: 'विश्लेषण, निगरानी और प्रबंधन',
    newToCivic: 'अर्बन लेंस में नए हैं?',
    createCitizenAccount: 'नागरिक खाता बनाएं →',
    aiDetection: 'AI पहचान',
    aiDetectionDesc: 'स्मार्ट गड्ढा और कूड़ा पहचान',
    geoDedup: 'जियो डुप्लिकेशन',
    geoDedupDesc: '10 मीटर के भीतर डुप्लिकेट रिपोर्ट रोकता है',
    gamification: 'गेमिफिकेशन',
    gamificationDesc: 'रिपोर्ट के लिए अंक और बैज कमाएं',
    wardRouting: 'वार्ड रूटिंग',
    wardRoutingDesc: 'समस्याएं सही नगरपालिका वार्ड में भेजी जाती हैं',
    teamCredit: 'टीम टेक्नो-5 · BMSCE हैकथॉन 2026',
    builtWith: 'AI + PostGIS + React Native से निर्मित',
    footerRights: '© 2026 अर्बन लेंस। सर्वाधिकार सुरक्षित।',
    footerMission: 'नागरिकों को स्मार्ट शहर बनाने में सशक्त करना।',
    language: 'भाषा',
  },
  kn: {
    appName: 'ಅರ್ಬನ್ ಲೆನ್ಸ್',
    tagline: 'AI-ಚಾಲಿತ ನಾಗರಿಕ ಮೂಲಸೌಕರ್ಯ ಟ್ರ್ಯಾಕರ್',
    heroDesc: 'ಗುಂಡಿಗಳು, ಕಸದ ರಾಶಿ ಮತ್ತು ಮುರಿದ ಬೀದಿ ದೀಪಗಳನ್ನು ವರದಿ ಮಾಡಿ. AI ಮೌಲ್ಯೀಕರಿಸುತ್ತದೆ ಮತ್ತು ನಿಮ್ಮ ನಗರಪಾಲಿಕೆ ವಾರ್ಡ್‌ಗೆ ಕಳುಹಿಸುತ್ತದೆ.',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    home: 'ಮುಖಪುಟ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    reportIssue: 'ನಾಗರಿಕ ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    citizen: 'ನಾಗರಿಕ',
    officer: 'ನಗರಪಾಲಿಕೆ ಅಧಿಕಾರಿ',
    admin: 'ನಿರ್ವಾಹಕ',
    selectRole: 'ಮುಂದುವರಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    welcome: 'ಮರಳಿ ಸ್ವಾಗತ',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    joinUrbanLens: 'ಅರ್ಬನ್ ಲೆನ್ಸ್ ಸೇರಿ',
    helpCity: 'ಸುರಕ್ಷಿತ, ಶುಚಿಯಾದ ನಗರ ನಿರ್ಮಿಸಲು ಸಹಾಯ ಮಾಡಿ',
    username: 'ಬಳಕೆದಾರ ಹೆಸರು',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    email: 'ಇಮೇಲ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    address: 'ವಿಳಾಸ',
    signIn: 'ಸೈನ್ ಇನ್',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    haveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    backToRoles: '← ಪಾತ್ರ ಆಯ್ಕೆಗೆ ಹಿಂತಿರುಗಿ',
    citizenLogin: 'ನಾಗರಿಕ ಲಾಗಿನ್',
    officerLogin: 'ಅಧಿಕಾರಿ ಲಾಗಿನ್',
    adminPortal: 'ನಿರ್ವಾಹಕ ಪೋರ್ಟಲ್',
    reportDesc: 'ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ ಮತ್ತು ಅಂಕಗಳನ್ನು ಗಳಿಸಿ',
    officerDesc: 'ನಿಯೋಜಿತ ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಪರಿಹರಿಸಿ',
    adminDesc: 'ವಿಶ್ಲೇಷಣೆ, ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ನಿರ್ವಹಣೆ',
    newToCivic: 'ಅರ್ಬನ್ ಲೆನ್ಸ್‌ಗೆ ಹೊಸಬರೇ?',
    createCitizenAccount: 'ನಾಗರಿಕ ಖಾತೆ ರಚಿಸಿ →',
    aiDetection: 'AI ಪತ್ತೆ',
    aiDetectionDesc: 'ಸ್ಮಾರ್ಟ್ ಗುಂಡಿ ಮತ್ತು ಕಸ ಗುರುತಿಸುವಿಕೆ',
    geoDedup: 'ಜಿಯೋ ಡಿಡಪ್ಲಿಕೇಶನ್',
    geoDedupDesc: '10m ಒಳಗೆ ನಕಲು ವರದಿಗಳನ್ನು ತಡೆಯುತ್ತದೆ',
    gamification: 'ಗ್ಯಾಮಿಫಿಕೇಶನ್',
    gamificationDesc: 'ವರದಿಗಳಿಗಾಗಿ ಅಂಕ ಮತ್ತು ಬ್ಯಾಡ್ಜ್ ಗಳಿಸಿ',
    wardRouting: 'ವಾರ್ಡ್ ರೂಟಿಂಗ್',
    wardRoutingDesc: 'ಸಮಸ್ಯೆಗಳು ಸರಿಯಾದ ನಗರಪಾಲಿಕೆ ವಾರ್ಡ್‌ಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ',
    teamCredit: 'ಟೀಮ್ ಟೆಕ್ನೋ-5 · BMSCE ಹ್ಯಾಕಥಾನ್ 2026',
    builtWith: 'AI + PostGIS + React Native ಯೊಂದಿಗೆ ನಿರ್ಮಿಸಲಾಗಿದೆ',
    footerRights: '© 2026 ಅರ್ಬನ್ ಲೆನ್ಸ್. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    footerMission: 'ಸ್ಮಾರ್ಟ್ ನಗರಗಳನ್ನು ನಿರ್ಮಿಸಲು ನಾಗರಿಕರನ್ನು ಸಬಲಗೊಳಿಸುವುದು.',
    language: 'ಭಾಷೆ',
  },
};

type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en', setLang: () => {}, t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');
  const t = (key: string) => translations[lang]?.[key] || translations.en[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() { return useContext(LanguageContext); }
export type { Lang };
